# infrastructure/kubernetes/base/loan-application/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-application
  namespace: fintech-loan-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-application
  template:
    metadata:
      labels:
        app: loan-application
        version: v1
    spec:
      containers:
      - name: loan-application
        image: fintech/loan-application:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: loan-db-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
