# infrastructure/kubernetes/base/credit-scoring/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring
  namespace: fintech-loan-processing
spec:
  replicas: 5  # 5x parallel processing mentioned in paper
  selector:
    matchLabels:
      app: credit-scoring
  template:
    metadata:
      labels:
        app: credit-scoring
        version: v1
    spec:
      containers:
      - name: credit-scoring
        image: fintech/credit-scoring:latest
        ports:
        - containerPort: 3003
        env:
        - name: JAVA_OPTS
          value: "-Xmx1g -Xms512m"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
